### ISSUE TITLE
Cosmos DB resource creation

### ISSUE THREAD

**Issue by katchme88** [serverless/serverless-azure-functions#100]
Hi contributors. Just wondering if anyone has a solution regarding creation of cosmos db resource on deploy. I did not get a solution to it and since many folks on other forums have been asking about the same question, I have solved the problem. If this issue has been resolved than that's great. If not, may be I could help. Please do let me know.

**Comment by PhilAndrew** [comment]
How did you solve it?

**Comment by katchme88** [comment]
I modified the resource template that serverless use to create resources. You'll find the arm resource template in one of the serverless azure module and add cosmos db to it. If you need further help on the resource templates, microsoft has a very thorough documentation on it.

**Comment by janisn** [comment]
@katchme88 
Could you upload your resource template with your modifications and how you included it into the serverless.yml file? That would be really helpful as I did not find much information about how to include an ARM template into the serverless service.

**Comment by abkruse** [comment]
@janisn I just had a similar struggle and have the ARM template in the provider object per the way it seemed to be referenced in the source code..
```
provider:
  name: azure
  location: West US
  armTemplate:
    file: azure-resources.json
    parameters: ${file(azure-resources.parameters.json)}
```
