### ISSUE TITLE
Unable to add direction in/out to blob trigger

### ISSUE THREAD

**Issue by raymondsze** [serverless/serverless-azure-functions#103]
```
service: function-app

provider:
  name: azure
  location: East Asia

plugins:
  - serverless-azure-functions

package:
  exclude:
    - node_modules/**
    - .gitignore
    - package.json
    - .git/**

functions:
  BlobTriggerImageThumbnails800x600:
    handler: handler.thumbnails800x600
    events:
    - blob:
      x-azure-settings:
        path: images/{name}
        connection: AzureWebJobsImageStorage
        name: blob
        direction: in
    - blob:
      x-azure-settings:
        path: image-thumbnails/800x600_{name}
        connection: AzureWebJobsImageStorage
        direction: out
```
would result in `Binding not found` in `shared/utils.js line: 71`

it attempts to find the key `blobTriggerIn_displayName` instead of `blobIn_displayName` in `bindingDisplayNames`
