### ISSUE TITLE
httpTrigger methods should be lowercase

### ISSUE THREAD

**Issue by jmendiara** [serverless/serverless-azure-functions#109]
Following the guide at https://serverless.com/framework/docs/providers/azure/guide/intro/, this  `serverless.yml`
```yml
functions:
  GetUserConsent:
    handler: lib/azure.getUserConsent
    events:
      - http: true
        x-azure-settings:
          authLevel : anonymous
          route: consents/{userId}
          methods:
            - GET
      - http: true
        x-azure-settings:
          direction: out
          name: res
```

generates this `function.json`
```json
{
    "disabled": false,
    "bindings": [
        {
            "type": "httpTrigger",
            "direction": "in",
            "name": "req",
            "route": "consents/{userId}",
            "authLevel": "anonymous",
            "methods": [
                "GET"
            ]
        },
        {
            "type": "http",
            "direction": "out",
            "name": "res"
        }
    ],
    "entryPoint": "getUserConsent"
}
```

But the portal UI shows no checkbox
![captura de pantalla 2018-01-24 a las 15 33 14](https://user-images.githubusercontent.com/851359/35337610-fb62c08a-011b-11e8-810d-973b4734f699.png)

And after clicking in the UI, the `function.json` seen in App Service Editor shows
<img width="657" alt="captura de pantalla 2018-01-24 a las 15 35 21" src="https://user-images.githubusercontent.com/851359/35337741-4450ac94-011c-11e8-880e-c2488c5fef85.png">
Note the duplicated `get` and `GET`

I think the generated `function.json` should  use the lowercase method name `get`
