### ISSUE TITLE
Allow App Service plans other than "Consumption"

### ISSUE THREAD

**Issue by denisw** [serverless/serverless-azure-functions#114]
In our current project, we have a serious problem with cold start time of our Azure function. For that reason, we'd like to use an "Always On" App Service plan instead of "Consumption", at least temporarily. 

However, the "Consumption" plan is currently hardcoded into this plugin. Would it be possible to make this configurable?

**Comment by wbreza** [comment]
@denisw - The azure plugin support defining a custom arm template that can be referenced in the `serverless.yml` where you have complete control over the plan hosting your function app.

It is not well documented as of now.

```
armTemplate:
  file: arm/template.json
  parameters:
    param1: value1
    param2: value2
```
