### ISSUE TITLE
Location is always West US, ignoring provider.location

### ISSUE THREAD

**Issue by e-compton** [serverless/serverless-azure-functions#303]
Hi I've been trying to deploy my functions to UK South region on Azure, but they always seem to get deployed to West US.

```
npx serverless deploy
```

```
"serverless-azure-functions": "^1.0.0-32"
```

serverless.yml
```
service: demo-services-api

provider:
  name: azure
  runtime: nodejs8.11.1
  location: UK South

plugins:
  - serverless-azure-functions

package:
  exclude:
    - local.settings.json
    - .vscode/**
    - .git

functions:
  myFunction:
    handler: index.myFunction
    events:
      - http: true
        x-azure-settings:
          authLevel: anonymous
      - http: true
        x-azure-settings:
          direction: out
          name: res
```

output
```
Serverless: Removing .serverless directory
Serverless: Parsing Azure Functions Bindings.json...
Serverless: Building binding for function: myFunction event: httpTrigger
Serverless: Building binding for function: myFunction event: http
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Logging into Azure
Serverless: Using subscription ID: 9b67a840-c0e8-4408-bcc7-90f61ea90ce2
Serverless: Creating resource group: sls-wus-dev-demo-services-api-rg
Serverless: Creating function app: demo-services-api
Serverless: -> Creating ARM template from type: consumption
Serverless: Listing deployments for resource group 'sls-wus-dev-demo-services-api-rg':
Serverless: Generated template same as previous. Skipping ARM deployment
Serverless: Deploying serverless functions...
Serverless: Deploying zip file to function app: sls-wus-dev-demo-services-api
Serverless: -> Deploying service package @ C:\Projects\serverless-test\.serverless\demo-services-api.zip
Serverless: Deployed serverless functions:
Serverless: -> myFunction : * sls-wus-dev-demo-services-api.azurewebsites.net/api/myFunction 
Serverless: Uploading file at 'C:\Projects\serverless-test\.serverless\demo-services-api.zip' to container 'deployment-artifacts' with name 'slswusdevdemoservicesapi-ARTIFACT-t1567585486198.zip'
Serverless: Finished uploading blob
Serverless: -> Function package uploaded successfully
```

Looking in the Azure Portal, I find that `sls-wus-dev-demo-services-api-rg` is a resource group in the West US region.

**Comment by e-compton** [comment]
The key has changed, so its `region` instead of `location`:
```
provider:
  name: azure
  runtime: nodejs8.11.1
  region: UK South
```
