### ISSUE TITLE
timer binding not using specified name

### ISSUE THREAD

**Issue by mydiemho** [serverless/serverless-azure-functions#307]
`binding.json` generated for timer not using specified name, always use `myTimer`

```yaml
functions:
  timer:
    handler: src/handlers/timer.printMessage
    events:
      - timer: sampleTimer
        x-azure-settings:
          schedule: '*/10 * * * * *'
```
the above code generate the following binding
```json
{
  "disabled": false,
  "bindings": [
    {
      "type": "timerTrigger",
      "direction": "in",
      "name": "myTimer",
      "schedule": "*/10 * * * * *"
    }
  ],
  "entryPoint": "printMessage",
  "scriptFile": "../src/handlers/timer.js"
}
```

but `name` should've been `sampleTimer`
