### ISSUE TITLE
support for cosmoDB in/out bindings

### ISSUE THREAD

**Issue by mydiemho** [serverless/serverless-azure-functions#346]
# This is a Feature Proposal

## Description

Similar to all other triggers, I should be able to add either in/out binding for CosmoDB by this

```yaml
      - cosmoDB:
        x-azure-settings:
          name: record # Name of the binding parameter that represents the document in the function.
          databaseName: MyDatabase # "<Name of the CosmoDB database>",
          collectionName: MyCollection # "<Name of the CosmoDB collection>",
          createIfNotExists: true
          connection: COSMODB_CONNECTION # "<Name of app setting app setting containing your Azure Cosmos DB connection string>",
          direction: out
```

Similar or dependent issues:
n/a
