### ISSUE TITLE
x-azure-settings does not support a setting with value set to false

### ISSUE THREAD

**Issue by itaym2** [serverless/serverless-azure-functions#35]
I tried deploying a function using the following serverless.yml:
```
service: my-service

provider:
  name: azure
  location: East US
  armTemplate:
     file: armTemplate.json
     parameters:
        functionAppName: my-app

plugins:
  - serverless-azure-functions

package:
  exclude:
    - node_modules/**
    - .gitignore
    - package.json
    - .git/**

functions:
  my-func: 
     handler: func.handler
     events: 
       - timer: 
         x-azure-settings:
           name: item 
           schedule: 0 */5 * * * * 
       - documentDB:
         x-azure-settings:
           connection: SETTING_FROM_ARM_TEMPLATE
           createIfNotExists: false #this is important 
           direction: out
           name: n
           databaseName: dbname
           collectionName: collname
```
when I executed the command "sls deploy", I got the following error:
_Required property createIfNotExists is missing for binding:documentDB_

After investigating the issue, I found the problem lies in utils.js, in the function getBinding.  
The problem is in the following if statement:
```
if (bindingUserSettings && bindingUserSettings[name]) {
        binding[name] = bindingUserSettings[name];
        continue;
}
```

Because I set the createIfNotExists setting value to false, the condition in the if statement wasn't matched, and because the createIfNotExists property is required, the deployment failed.

The fix is simple, change the condition in the if statement to:
```
if (bindingUserSettings && (bindingUserSettings[name] !== undefined && bindingUserSettings[name] !== null))
```

I can create a pull request if this issue will be accepted.
