### ISSUE TITLE
Incorrect Service Bus Out binding

### ISSUE THREAD

**Issue by stout01** [serverless/serverless-azure-functions#352]
# This is a Bug Report

## Description

- What went wrong?
  - A default queueName is added to the function.json along with the specified topicName
- What did you expect should have happened?
  - The queueName should not be included in the function.json
- What was the config you used?
```yaml
save-condition:
  handler: src/handlers/save-condition.handler
  name: save-condition
  events:
    - http: true
      x-azure-settings:
        methods:
          - POST
        authLevel: anonymous
        route: conditions
    - serviceBus:
      x-azure-settings:
        direction: out
        name: conditionsTopic
        topicName: condition-saved
        connection: ServiceBusConnection
```
- What stacktrace or error message from your provider did you see?
  - function.json
```json
{
  "disabled": false,
  "bindings": [
    {
      "type": "httpTrigger",
      "direction": "in",
      "name": "req",
      "route": "conditions",
      "authLevel": "anonymous",
      "methods": [
        "POST"
      ]
    },
    {
      "type": "serviceBus",
      "direction": "out",
      "name": "conditionsTopic",
      "queueName": "outqueue",
      "topicName": "condition-saved",
      "connection": "ServiceBusConnection",
      "accessRights_": "Manage"
    }
  ],
  "entryPoint": "handler",
  "scriptFile": "..\\src\\handlers\\save-condition.js"
}
```
  - `Microsoft.Azure.ServiceBus: Put token failebus.windows.net:outqueue, Timestamp:2019-09-30T16:35:11.ed. status-code: 404, status-description: The messaging entity 'sb://service-bus-name-here.servicebus.windows.net/outqueue' could not be found`

Similar or dependent issues:

- #57 

## Additional Data

- **_Serverless Framework Version you're using_**:
  - 1.53.0
- **_Serverless CLI Version you're using_**:
  - 1.2.3
- **_Serverless Azure Plugin Version you're using_**:
  - 1.0.2-4
- **_Operating System_**:
  - Windows 10
- **_Stack Trace_**:
- **_Provider Error messages_**:
