### ISSUE TITLE
eventHub trigger not working on azure portal

### ISSUE THREAD

**Issue by leopuleo** [serverless/serverless-azure-functions#361]
# This is a Bug Report

## Description

- What went wrong?
I successfully deploy my serverless functions to Azure, setting eventHub as binding. 
While I visit the function page on azure an error appears and the function does not work:

```
Error: Microsoft.Azure.WebJobs.Host: Error indexing method 'Functions.myfunc'. Microsoft.Azure.WebJobs.EventHubs: Value cannot be null. Parameter name: receiverConnectionString.
``` 
- What did you expect should have happened?
The function to work correctly
- What was the config you used?
serverless.yml
```
myfunc:
        handler: src/entrypoint.myfunc
        events:
            - eventHub:
              x-azure-settings:
                  name: items # Specifies which name it's available on `context`
                  eventHubName: myfunc-events # Specifies the Name of the Event Hub
                  consumerGroup: myfuncchannel # Specifies the consumerGroup to listen with
                  connection: ${opt:eh} # App Setting/environment variable which contains Event Hubs Namespace Connection String
```
- What stacktrace or error message from your provider did you see?
function.json
````
{
  "disabled": false,
  "bindings": [
    {
      "type": "eventHubTrigger",
      "direction": "in",
      "name": "items",
      "eventHubName": "myfunc-events",
      "consumerGroup": "myfuncchannel",
      "connection": "Endpoint={myurl}"
    }
  ],
  "entryPoint": "myfunc",
  "scriptFile": "../src/entrypoint.js"
}
````
```
Error: Microsoft.Azure.WebJobs.Host: Error indexing method 'Functions.myfunc'. Microsoft.Azure.WebJobs.EventHubs: Value cannot be null. Parameter name: receiverConnectionString.
``` 
Similar or dependent issues:

- #352

## Additional Data

- **_Serverless Framework Version you're using_**: 1.54.0
- **_Serverless CLI Version you're using_**: 1.2.3
- **_Serverless Azure Plugin Version you're using_**: 1.0.2
- **_Operating System_**: darwin

**Comment by mydiemho** [comment]
@leopuleo

1. can you share your `src/entrypoint.js`?
1. When you say "visit the function page on azure", do you mean accessing the function url? 
1. The error is saying that you did not provide the connection string for your EventHub service.  
    * Base on your `serverless.yml` snippet, you're trying to pass in the connection string from the command line.  
   * How are you deploying the app?  Can you provide the full command used (masking any secrets)?

**Comment by leopuleo** [comment]
Hi @mydiemho,

> 1) can you share your src/entrypoint.js?

**/src/entrypoint.js**
```
import { myfuncChannel } from "./channels/myfunc";

export function myfunc(context, items) {
    return myfuncChannel(context, items);
}
```

**/channels/myfunc.js**
```
export const myfuncChannel = async (context, items) => {
    try {
        const messages = Array.isArray(items) ? items : [items];
        ...
        context.done();
    } catch (error) {
        context.done(error.message, { status: 500 });
    }
};
```
> 2) When you say "visit the function page on azure", do you mean accessing the function url?

No, the actual page on Azure Portal (see screenshot attached).

![Screenshot 2019-10-17 at 09 25 25](https://user-images.githubusercontent.com/2866531/66988533-fbc7ae80-f0c2-11e9-8fa8-990a700cbb9c.png)

Also, I noticed inside the "Integrate" tab the "EventHub connection" input is empty

![Screenshot 2019-10-17 at 09 25 51](https://user-images.githubusercontent.com/2866531/66988548-02562600-f0c3-11e9-99a6-2679b6489786.png)

> 3) The error is saying that you did not provide the connection string for your EventHub service.

**serverless.yml**

```
service: channels

provider:
    name: azure
    runtime: nodejs10.x
    region: ${opt:region, 'westeurope'}
    stage: ${opt:stage, 'dev'}
    prefix: ${opt:prefix, 'ncs'}
    environment:
        AZURE_EH_CONNECTION_STRING: ${opt:eh}
        BRANCH_NAME: ${opt:stage}

plugins:
    - serverless-azure-functions
    - serverless-webpack

custom:
    webpack:
        webpackConfig: "webpack.config.js" # Name of webpack configuration file
        includeModules: false # Node modules configuration for packaging
        packager: "npm" # Packager that will be used to package your external modules
        excludeFiles: "tests/**/**/*.js" # Provide a glob for files to ignore

functions:
    myfunc:
        handler: src/entrypoint.myfunc
        events:
            - eventHub:
              x-azure-settings:
                  name: items
                  eventHubName: myfunc-events
                  consumerGroup: myfuncchannel 
                  connection: ${opt:eh} 
```

**serverless cmd**

```
serverless deploy --region westeurope --stage dev --eh "Endpoint=sb://{myEHconnectionString}" --verbose
```
I also tried to set the full connection string inside the `serverless.yml, with no success.
Thank you!
