### ISSUE TITLE
Remove `x-azure-settings` from function configuration

### ISSUE THREAD

**Issue by tbarlow12** [serverless/serverless-azure-functions#371]
# This is a Feature Proposal

## Description

- Currently, the configuration for a function includes `x-azure-settings` as a property, and any function binding metadata exists as a child to that property.
- This is a proposition to eliminate `x-azure-settings` from the function configuration and instead make its sub-settings children of the trigger-type name. For example, the configuration

```yml
functions:
  hello:
    handler: hello/hello.main
    events:
      - http: true
        x-azure-settings:
          methods:
            - GET
          authLevel: anonymous
```
would become:
```yml
functions:
  hello:
    handler: hello/hello.main
    events:
      - http:
          methods:
             - GET
          authLevel: anonymous
```
and the configuration:
```yml
storageBlob:
    handler: src/handlers/storageBlob
    events:
      - blob:
        x-azure-settings:
          name: blob
          path: blob-sample/{blobName}
          connection: AzureWebJobsStorage
```
would become:
```yml
storageBlob:
    handler: src/handlers/storageBlob
    events:
      - blob:
          name: blob
          path: blob-sample/{blobName}
          connection: AzureWebJobsStorage
```

This also would remove the `http: true` for HTTP triggers, which is inconsistent with the rest of the triggers. Its existence would imply `true`

Similar or dependent issues:

- #12 
- #37 
- #38
