### ISSUE TITLE
Azure Function Slot Deployment

### ISSUE THREAD

**Issue by tbarlow12** [serverless/serverless-azure-functions#372]
# This is a Feature Proposal

## Description

- [Slots](https://docs.microsoft.com/en-us/azure/azure-functions/functions-deployment-slots) are instrumental in any sort of canary/blue-green deployment scenario. We want to support slot deployment and slot swapping
- Slots should be configurable via both `serverless.yml` and the CLI.

### Serverless.yml Configuration

```yml
...
provider:
  deployment:
    slot:
      name: {slotName}
      # Swaps slots as soon as deployment has finished, default false
      autoSwap: {true|false}
      # Defines rule for progressively swapping slot (mutually exclusive with `autoSwap`)
      # Increase traffic to slot by 5% every 10 minutes until at 50%, then swap completely
      progressiveSwap: 5 10 50
...
```
This would assume that deployments are always targeting a slot. It would allow users to never actually deploy to production, but instead deploy to a slot and test first to improve reliability. Azure functions handles "deployment" to production by just running a swap

### CLI Configuration

```bash
$ sls deploy --slot {slotName} --autoSwap {true|false} --progressiveSwap "5 10 50"
```

Also, there should be a CLI command for swapping slots:

```bash
$ sls swap slot --from staging --target production
```

Totally open to feedback on configuration values/names.

Similar or dependent issues:

- #297
