### ISSUE TITLE
Function-local environment variables not set by OfflineService

### ISSUE THREAD

**Issue by lukiffer** [serverless/serverless-azure-functions#407]
# This is a Bug Report

## Description

- What went wrong?

An environment variable defined at the `function:` level does not get included in the environment. Only environment variables defined at the `provider:` level are appended.

See: https://github.com/serverless/serverless-azure-functions/blob/master/src/services/offlineService.ts#L75-L80

- What did you expect should have happened?

The offline environment should behave similarly to the production environment in that `provider`-level environment variables are available on all functions, and `function`-level environment variables are available only on the functions on which they're defined.

- What was the config you used?

```yaml
service: example
frameworkVersion: "^1.61"

provider:
  name: azure
  location: Central US
  runtime: nodejs10.x
  environment:
    TEST_GLOBAL: global

plugins:
  - serverless-azure-functions

functions:
  example:
    description: example
    handler: handler.hello
    environment:
      TEST_LOCAL: local
    events:
      - http: true
        x-azure-settings:
          route: test
          methods:
            - get
          authLevel: anonymous
```

- What stacktrace or error message from your provider did you see?

Similar or dependent issues:

## Additional Data

- **_Serverless Framework Version you're using_**: 1.61.3
- **_Serverless CLI Version you're using_**: 1.4.0
- **_Serverless Azure Plugin Version you're using_**: 1.0.2
- **_Operating System_**: macOS Mojave
- **_Stack Trace_**: N/A
- **_Provider Error messages_**: N/A
