### ISSUE TITLE
Error when deploying linux funcapp node10/12

### ISSUE THREAD

**Issue by grizzly-monkey** [serverless/serverless-azure-functions#437]
# This is a Bug Report
Yes
## Description
When using azure function 1.0.2-23 to deploy functionApp with linux os node10/12 getting error.
- What went wrong?
- What did you expect should have happened?
- What was the config you used?
    ```provider:
  name: azure
  os: linux
  region: Central US
  runtime: nodejs10
  prefix: "td-gnu"
  type: premium
- What stacktrace or error message from your provider did you see?
``` 
  Error --------------------------------------------------
 
  Error: DeploymentFailed - At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.------------------------
  DEPLOYMENT ERROR DETAILS
  ------------------------
  
  BadRequest - {
    "Code": "BadRequest",
    "Message": "The parameter LinuxFxVersion has an invalid value.",
    "Target": null,
    "Details": [
      {
        "Message": "The parameter LinuxFxVersion has an invalid value."
      },
      {
        "Code": "BadRequest"
      },
      {
        "ErrorEntity": {
          "ExtendedCode": "01007",
          "MessageTemplate": "The parameter {0} has an invalid value.",
          "Parameters": [
            "LinuxFxVersion"
          ],
          "Code": "BadRequest",
          "Message": "The parameter LinuxFxVersion has an invalid value."
        }
      }
    ],
    "Innererror": null
  }
      at ArmService.<anonymous> (/Users/jp250090/Documents/teradata/draas/azure-agent-proxy/node_modules/serverless-azure-functions/lib/services/armService.js:235:39)
      at step (/Users/jp250090/Documents/teradata/draas/azure-agent-proxy/node_modules/serverless-azure-functions/lib/services/armService.js:56:23)
      at Object.next (/Users/jp250090/Documents/teradata/draas/azure-agent-proxy/node_modules/serverless-azure-functions/lib/services/armService.js:37:53)
      at fulfilled (/Users/jp250090/Documents/teradata/draas/azure-agent-proxy/node_modules/serverless-azure-functions/lib/services/armService.js:28:58)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
  From previous event:
      at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:490:22)
      at /usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:525:24
  From previous event:
      at PluginManager.run (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:525:8)
      at /usr/local/lib/node_modules/serverless/lib/Serverless.js:133:33
      at processImmediate (internal/timers.js:456:21)
      at process.topLevelDomainCallback (domain.js:137:15)
  From previous event:
      at Serverless.run (/usr/local/lib/node_modules/serverless/lib/Serverless.js:120:74)
      at /usr/local/lib/node_modules/serverless/bin/serverless.js:82:30
      at /usr/local/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:136:16
      at /usr/local/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:57:14
      at FSReqCallback.oncomplete (fs.js:159:23)
  From previous event:
      at /usr/local/lib/node_modules/serverless/bin/serverless.js:82:8
      at processImmediate (internal/timers.js:456:21)
      at process.topLevelDomainCallback (domain.js:137:15)
  From previous event:
      at Object.<anonymous> (/usr/local/lib/node_modules/serverless/bin/serverless.js:71:4)
      at Module._compile (internal/modules/cjs/loader.js:1147:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
      at Module.load (internal/modules/cjs/loader.js:996:32)
      at Function.Module._load (internal/modules/cjs/loader.js:896:14)
      at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
      at internal/main/run_main_module.js:17:47
 
```
Similar or dependent issues:

- #12345

## Additional Data
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              13.12.0
     Framework Version:         1.67.3
     Plugin Version:            3.6.6
     SDK Version:               2.3.0
     Components Version:        2.29.3

- **_Serverless Framework Version you're using_**: 1.67.3
- **_Serverless CLI Version you're using_**:
- **_Serverless Azure Plugin Version you're using_**: 1.0.2-23 
- **_Operating System_**:darwin
- **_Stack Trace_**:
- **_Provider Error messages_**:

**Comment by tbarlow12** [comment]
@grizzly-monkey thanks for opening this issue. I just repro'd on my end and will start investigating

**Comment by jeicob22** [comment]
Hello :)

I have the same issue here.
Seems to be independent of the runtime, it crashes with that error when defining **os: linux** (tested on all nodejs and python runtimes)

**Comment by tbarlow12** [comment]
Good to know. Syncing up with the Azure Functions team to see what changed

**Comment by tbarlow12** [comment]
@jeicob22 I was able to deploy a python function fine. Maybe share your config?

**Comment by jeicob22** [comment]
Sure, my serverless.yml file was:

```yaml

# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: megatest-num2

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: azure
  location: West Europe
  region: westeurope
  runtime: nodejs12
  # runtime: "python3.7"
  os: "linux"
  resourceGroup: my-rg-name-jeicob22-rg
  environment:
    TEST_URL: 'https://mytest.online.local'


plugins: # look for additional plugins in the community plugins repo: https://github.com/serverless/plugins
  - serverless-azure-functions

# you can add packaging information here
package:
  # include:
  #   - include-me.js
  #   - include-me-dir/**
  exclude:
    # - exclude-me.js
    # - exclude-me-dir/**
    - local.settings.json
    - .vscode/**

functions:
  hello:
    handler: src/handlers/hello.sayHello
    # handler: src/handlerspython/hello.my_function
    events:
      - http: true
        x-azure-settings:
          methods:
            - GET
          authLevel: anonymous # can also be `function` or `admin`
```

Could be possible that I'm missing something. I'm relativelly new to Serverless framework.

Thanks @tbarlow12
