### ISSUE TITLE
return bindings must specify a direction of 'out' 

### ISSUE THREAD

**Issue by kokokenada** [serverless/serverless-azure-functions#447]
# This is a Bug Report

## Description

When running sls offline, an error was thrown and it was not obvious what corrective action is needed and perhaps it is a bug.

## Additional Data

- **_Serverless Framework Version you're using_**:
````
sls --version
Framework Core: 1.67.0
Plugin: 3.5.0
SDK: 2.3.0
Components: 2.22.3
````
- **_Serverless CLI Version you're using_**:
- **_Serverless Azure Plugin Version you're using_**:
1.0.2
- **_Operating System_**:
Mac Os 10.15.2
- **_Stack Trace_**:
N/A
- **_Provider Error messages_**:
````
[2020-04-29 11:15:17 PM] The 'auth' function is in error: $return bindings must specify a direction of 'out'.
[2020-04-29 11:15:17 PM] The 'api' function is in error: $return bindings must specify a direction of 'out'.

````
serverless.yml:
````
service:
  name: csa-api
  # app and org for use with dashboard.serverless.com
  app: csa-api
  org: XXX

# Add the serverless-webpack plugin
plugins:
  - serverless-offline
  - serverless-domain-manager
  - serverless-azure-functions

provider:
  stage: ${env:REACT_APP_GIT_BRANCH, 'dev'}
  name: azure
  runtime: nodejs10.x
  region: ${opt:region, 'West US'} # Overwrite the default region used.
  apim:
    apis:
      - name: csa-api
        # Require an API Key if true
        subscriptionRequired: false
        displayName: CSA API
        description: The Citzen Support App API
        protocols:
          - https
        # Defaults to /api
        path: ${env:REACT_APP_GIT_BRANCH, 'dev'}
        # Azure resource tags
        tags:
          - csa
          - api
        authorization: none
    backends:
      - name: csa-backend
        url: api/csa
    cors:
      allowCredentials: false
      allowedOrigins:
        - "*"
      allowedMethods:
        - GET
        - POST
        - PUT
        - DELETE
        - PATCH
      allowedHeaders:
        - "*"
      exposeHeaders:
        - "*"

functions:
  auth:
    name: csa-auth-${env:REACT_APP_GIT_BRANCH}
    handler: build/src/graphql.handler
    events:
      - http: true
        x-azure-settings:
          authLevel: anonymous
          methods:
          - GET
          name: $return
    apim:
      api: csa-api
      backend: csa-backend
  api:
    name: csa-api-${env:REACT_APP_GIT_BRANCH}
    handler: build/src/graphql.handler
    events:
      - http:
        method: get
        path: /api
        x-azure-settings:
          authLevel: anonymous
          name: $return
          methods:
            - GET
            - POST
    apim:
      api: csa-api
      backend: csa-backend

package: # Optional deployment packaging configuration
  include: # Specify the directories and files which should be included in the deployment package
    - dist/**
    - node_modules
  exclude: # Specify the directories and files which should be excluded in the deployment package
    - src/**

````
