### ISSUE TITLE
Looking for a JavaScript while deploying a C# application 

### ISSUE THREAD

**Issue by Jorriss** [serverless/serverless-azure-functions#45]
I'm trying to test out deploying a C# application to Azure and running into this error:

```
ENOENT: no such file or directory, stat 'c:\\Code\LogLoader\LoadLogData\functions\run.js'
```

I'm pretty sure I'm missing something in my serverless.yml file

```
service: AFTKLogLoader

provider:
  name: azure
  location: West US

plugins:
  - serverless-azure-functions

package:
  exclude:
    - env.bat
    - .gitignore
    - package.json
    - .git/**
 
functions:
  LogLoader: 
     handler: functions/run.csx
```

Is there any documentation or examples that would assist creating a C# application in Azure?
