### ISSUE TITLE
Skip APIM ARM deployment

### ISSUE THREAD

**Issue by Rapol** [serverless/serverless-azure-functions#476]
# This is a Feature Proposal

## Description

We would like to add an option to exclude the APIM resource in the ARM template when using the `type`(consumption, premium, ase) deployment. 

We have multiple function apps reusing resources (app service plan, apim, storage accounts, etc) in a resource group. This has been working for us nicely but we encountered an issue with APIM. We needed to set the APIM in a VNET. Both of these were created via scripts outside of serverless. When we reference the APIM name in the serverless config it works perfectly but since serverless doesn't know about the VNET the resulting ARM template wipes out the VNET configuration.

I forked the repo and made a branch with the changes we were envisioning but I haven't tested it yet. https://github.com/Rapol/serverless-azure-functions/commit/3b1e09d113871ee7fcaaed3c07124b6a7935d074

Another option would be to add APIM VNET configuration into the apim section in the provider and update the default APIM template to reflect this. For our use case it sounds better to deploy the APIM and VNET configuration outside of serverless and just use serverless to update the APIM endpoint integration with the function apps.

**Comment by arsenvlad** [comment]
I am also trying to see if one APIM can be used with multiple separate function apps. @Rapol when you tried re-using the APIM, did you notice it also overwriting the API and backend definitions or have those stayed OK for you and only VNET config was wiped out?

**Comment by Rapol** [comment]
The apim definitions stayed even after deployments of different sls projects. Only the vnet config was wiped out. I suppose the backend definitions cannot be named the same across sls projects, that might overwrite them. 

Our sls config imports a config that has the name of the resources (apim, storage accounts, etc). This will make the azure plugin to use the same resources across sls projects. Note that the apim config below has a skipArmTemplate property which is part of the fork I posted in the original issue. This will tell the plugin to not add the APIM to the ARM template but it will still update the APIM endpoints since thats done via the azure cli and not ARM. Keep in mind that now you will need to deploy the APIM individually if skipArmTemplate = true.

```
provider:
  name: azure
  runtime: nodejs10.x
  tenantId: ${self:custom.config.tenantId}
  os: linux
  resourceGroup: ${opt:rg, self:custom.config.resourceGroup}
  region: ${opt:region, 'East US 2'}
  stage: ${opt:stage, 'dev'}
  subscriptionId: ${self:custom.config.subscriptionId}
  type: premium
  appServicePlan:
    name: ${self:custom.config.servicePlanName}
    sku:
      tier: ElasticPremium
      name: EP1
  appInsights:
    name: ${self:custom.config.appInsightsName}
  functionApp:
    name: ${self:custom.config.functionAppName}
  storageAccount:
    name: ${self:custom.config.storageName}
  apim:
    # Name of a previously deployed APIM
    name: ${self:custom.config.apimName}
    skipArmTemplate: true
    sku:
      name: ${self:custom.config.apimSku}
      capacity: 1
    apis:
      - name: users-api
    ....
```
