### ISSUE TITLE
TypeError: Cannot read property 'x-azure-settings' of undefined

### ISSUE THREAD

**Issue by genesis-TdP** [serverless/serverless-azure-functions#477]
# This is a Bug Report

## Description

- What went wrong? 
Create my serverless project and run the command sls offline and it gives me error: TypeError: Cannot read property 'x-azure-settings' of undefined 

- What stacktrace or error message from your provider did you see?

```
Serverless: Building binding for function: hello event: httpTrigger

  Type Error ---------------------------------------------

  TypeError: Cannot read property 'x-azure-settings' of undefined
      at PackageService.createBinding (C:\Users\Documents\everis\function-genesis-demo\node_modules\serverless-azure-functions\lib\services\packageService.js:151:90)
Similar or dependent issues:
```

## Additional Data

My Environment Information ---------------------------
     Operating System:          win32
     Node Version:              12.18.1
     Framework Version:         1.73.1
     Plugin Version:            3.6.13
     SDK Version:               2.3.1
     Components Version:        2.30.15

**Comment by tbarlow12** [comment]
@genesis-TdP can you post your `serverless.yml` config?

**Comment by psurma** [comment]
I am getting the same thing
`  TypeError: Cannot read property 'x-azure-settings' of undefined`
simply by:

```
serverless create --template azure-nodejs --path tester
cd tester
npm i
sls deploy
```
I had to change the runtime from `nodejs12.x` to `nodejs10.6.0` due to "Error: Runtime nodejs12.x is not supported. Supported versions"

 ```
 Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              12.15.0
     Framework Version:         1.74.1
     Plugin Version:            3.6.14
     SDK Version:               2.3.1
     Components Version:        2.31.7
```

**Comment by alissonphp** [comment]
I have the same problem here

```
Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              10.20.1
     Framework Version:         1.74.1
     Plugin Version:            3.6.15
     SDK Version:               2.3.1
     Components Version:        2.31.10
```

**Comment by getfatday** [comment]
@genesis-TdP same issue as well. 

```
node@12.16.2
azure-functions-core-tools@2.7.2628
serverless-azure-functions@1.0.2
```

Running the following produces an error:
``` sh
sls create -t azure-nodejs -p hello
cd hello
yarn install
sls offline
```

Without any modifications, the CLI returns this error:
``` sh

  Error --------------------------------------------------

  Error: Runtime nodejs12.x is not supported. Supported versions: {
    "nodejs": [
      {
        "version": "0.10.40"
      },
      {
        "version": "0.10.5"
      },
      {
        "version": "0.12.6"
      },
      {
        "version": "0.6.20"
      },
      {
        "version": "0.8.28"
      },
      {
        "version": "10.14.1"
      },
      {
        "version": "10.15.2"
      },
      {
        "version": "10.6.0"
      },
      {
        "version": "4.8.4"
      },
      {
        "version": "6.12.3"
      },
      {
        "version": "6.5.0"
      },
      {
        "version": "6.9.1"
      },
      {
        "version": "6.9.5"
      },
      {
        "version": "7.10.1"
      },
      {
        "version": "8.1.4"
      },
      {
        "version": "8.10.0"
      },
      {
        "version": "8.11.1"
      },
      {
        "version": "8.4.0"
      },
      {
        "version": "8.5.0"
      },
      {
        "version": "8.9.4"
      }
    ],
    "python": [
      {
        "version": "3.6"
      }
    ]
  }
      at ConfigService.getRuntime (~/src/hello/node_modules/serverless-azure-functions/lib/services/configService.js:182:19)
      at ConfigService.initializeConfig (~/src/hello/node_modules/serverless-azure-functions/lib/services/configService.js:158:48)
      at new ConfigService (~/src/hello/node_modules/serverless-azure-functions/lib/services/configService.js:32:28)
      at OfflineService.BaseService (~/src/hello/node_modules/serverless-azure-functions/lib/services/baseService.js:67:30)
      at new OfflineService (~/src/hello/node_modules/serverless-azure-functions/lib/services/offlineService.js:84:28)
      at AzureOfflinePlugin.<anonymous> (~/src/hello/node_modules/serverless-azure-functions/lib/plugins/offline/azureOfflinePlugin.js:112:42)
      at step (~/src/hello/node_modules/serverless-azure-functions/lib/plugins/offline/azureOfflinePlugin.js:45:23)
      at Object.next (~/src/hello/node_modules/serverless-azure-functions/lib/plugins/offline/azureOfflinePlugin.js:26:53)
      at ~/src/hello/node_modules/serverless-azure-functions/lib/plugins/offline/azureOfflinePlugin.js:20:71
      at new Promise (<anonymous>)
      at __awaiter (~/src/hello/node_modules/serverless-azure-functions/lib/plugins/offline/azureOfflinePlugin.js:16:12)
      at AzureOfflinePlugin.azureOfflineBuild (~/src/hello/node_modules/serverless-azure-functions/lib/plugins/offline/azureOfflinePlugin.js:107:16)
      at ~/.config/yarn/global/node_modules/serverless/lib/classes/PluginManager.js:489:55
      at tryCatcher (~/.config/yarn/global/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
      at Object.gotValue (~/.config/yarn/global/node_modules/serverless/node_modules/bluebird/js/release/reduce.js:168:18)
      at Object.gotAccum (~/.config/yarn/global/node_modules/serverless/node_modules/bluebird/js/release/reduce.js:155:25)
      at Object.tryCatcher (~/.config/yarn/global/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (~/.config/yarn/global/node_modules/serverless/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (~/.config/yarn/global/node_modules/serverless/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromiseCtx (~/.config/yarn/global/node_modules/serverless/node_modules/bluebird/js/release/promise.js:641:10)
      at _drainQueueStep (~/.config/yarn/global/node_modules/serverless/node_modules/bluebird/js/release/async.js:97:12)
      at _drainQueue (~/.config/yarn/global/node_modules/serverless/node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (~/.config/yarn/global/node_modules/serverless/node_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues (~/.config/yarn/global/node_modules/serverless/node_modules/bluebird/js/release/async.js:15:14)
      at processImmediate (internal/timers.js:456:21)
      at process.topLevelDomainCallback (domain.js:137:15)

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              12.16.2
     Framework Version:         1.73.1
     Plugin Version:            3.6.13
     SDK Version:               2.3.1
     Components Version:        2.31.3
```

Updating the `serverless.yml` runtime to ` nodejs10.x`

``` diff
provider:
  name: azure
  region: West US 2
-  runtime: nodejs12.x
+  runtime: nodejs10.x
```

Causes the issue as described here:
```
Serverless: Building offline service
Serverless: Parsing Azure Functions Bindings.json...
Serverless: Building binding for function: hello event: httpTrigger

  Type Error ---------------------------------------------

  TypeError: Cannot read property 'x-azure-settings' of undefined
      at PackageService.createBinding (~/src/hello/node_modules/serverless-azure-functions/lib/services/packageService.js:151:90)
      at ~/src/hello/node_modules/serverless-azure-functions/lib/services/packageService.js:87:42
      at Array.map (<anonymous>)
      at PackageService.<anonymous> (~/src/hello/node_modules/serverless-azure-functions/lib/services/packageService.js:85:30)
      at step (~/src/hello/node_modules/serverless-azure-functions/lib/services/packageService.js:45:23)
      at Object.next (~/src/hello/node_modules/serverless-azure-functions/lib/services/packageService.js:26:53)
      at ~/src/hello/node_modules/serverless-azure-functions/lib/services/packageService.js:20:71
      at new Promise (<anonymous>)
      at __awaiter (~/src/hello/node_modules/serverless-azure-functions/lib/services/packageService.js:16:12)
      at PackageService.createBindings (~/src/hello/node_modules/serverless-azure-functions/lib/services/packageService.js:78:16)
      at OfflineService.<anonymous> (~/src/hello/node_modules/serverless-azure-functions/lib/services/offlineService.js:105:66)
      at step (~/src/hello/node_modules/serverless-azure-functions/lib/services/offlineService.js:56:23)
      at Object.next (~/src/hello/node_modules/serverless-azure-functions/lib/services/offlineService.js:37:53)
      at ~/src/hello/node_modules/serverless-azure-functions/lib/services/offlineService.js:31:71
      at new Promise (<anonymous>)
      at __awaiter (~/src/hello/node_modules/serverless-azure-functions/lib/services/offlineService.js:27:12)
      at OfflineService.build (~/src/hello/node_modules/serverless-azure-functions/lib/services/offlineService.js:98:16)
      at AzureOfflinePlugin.<anonymous> (~/src/hello/node_modules/serverless-azure-functions/lib/plugins/offline/azureOfflinePlugin.js:113:61)
      at step (~/src/hello/node_modules/serverless-azure-functions/lib/plugins/offline/azureOfflinePlugin.js:45:23)
      at Object.next (~/src/hello/node_modules/serverless-azure-functions/lib/plugins/offline/azureOfflinePlugin.js:26:53)
      at ~/src/hello/node_modules/serverless-azure-functions/lib/plugins/offline/azureOfflinePlugin.js:20:71
      at new Promise (<anonymous>)
      at __awaiter (~/src/hello/node_modules/serverless-azure-functions/lib/plugins/offline/azureOfflinePlugin.js:16:12)
      at AzureOfflinePlugin.azureOfflineBuild (~/src/hello/node_modules/serverless-azure-functions/lib/plugins/offline/azureOfflinePlugin.js:107:16)
      at ~/.config/yarn/global/node_modules/serverless/lib/classes/PluginManager.js:489:55
      at tryCatcher (~/.config/yarn/global/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
      at Object.gotValue (~/.config/yarn/global/node_modules/serverless/node_modules/bluebird/js/release/reduce.js:168:18)
      at Object.gotAccum (~/.config/yarn/global/node_modules/serverless/node_modules/bluebird/js/release/reduce.js:155:25)
      at Object.tryCatcher (~/.config/yarn/global/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (~/.config/yarn/global/node_modules/serverless/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (~/.config/yarn/global/node_modules/serverless/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromiseCtx (~/.config/yarn/global/node_modules/serverless/node_modules/bluebird/js/release/promise.js:641:10)
      at _drainQueueStep (~/.config/yarn/global/node_modules/serverless/node_modules/bluebird/js/release/async.js:97:12)
      at _drainQueue (~/.config/yarn/global/node_modules/serverless/node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (~/.config/yarn/global/node_modules/serverless/node_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues (~/.config/yarn/global/node_modules/serverless/node_modules/bluebird/js/release/async.js:15:14)
      at processImmediate (internal/timers.js:456:21)
      at process.topLevelDomainCallback (domain.js:137:15)

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              12.16.2
     Framework Version:         1.73.1
     Plugin Version:            3.6.13
     SDK Version:               2.3.1
     Components Version:        2.31.3
```

Here is the full `serverless.yml` file:

``` yaml
# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: hello

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: azure
  region: West US 2
  runtime: nodejs12.x
  # os: windows  # windows is default, linux is available
  # prefix: "sample"  # prefix of generated resource name
  # subscriptionId: A356AC8C-E310-44F4-BF85-C7F29044AF99
  # stage: dev
  # type: premium  # premium azure functions

  environment: # these will be created as application settings
    VARIABLE_FOO: 'foo'

  # you can define apim configuration here
  # apim:
  #   apis:
  #     - name: v1
  #       subscriptionRequired: false # if true must provide an api key
  #       displayName: v1
  #       description: V1 sample app APIs
  #       protocols:
  #         - https
  #       path: v1
  #       tags:
  #         - tag1
  #         - tag2
  #       authorization: none
  #   cors:
  #     allowCredentials: false
  #     allowedOrigins:
  #       - "*"
  #     allowedMethods:
  #       - GET
  #       - POST
  #       - PUT
  #       - DELETE
  #       - PATCH
  #     allowedHeaders:
  #       - "*"
  #     exposeHeaders:
  #       - "*"

plugins: # look for additional plugins in the community plugins repo: https://github.com/serverless/plugins
  - serverless-azure-functions

# you can add packaging information here
package:
  # include:
  #   - include-me.js
  #   - include-me-dir/**
  exclude:
    # - exclude-me.js
    # - exclude-me-dir/**
    - local.settings.json
    - .vscode/**

functions:
  hello:
    handler: src/handlers/hello.sayHello
    events:
      - http: true
        methods:
          - GET
        authLevel: anonymous # can also be `function` or `admin`

  goodbye:
    handler: src/handlers/goodbye.sayGoodbye
    events:
      - http: true
        methods:
          - GET
        authLevel: anonymous
  # The following are a few examples of other events you can configure:
  # storageBlob:
  #   handler: src/handlers/storageBlob.printMessage
  #   events:
  #     - blob:
  #       x-azure-settings:
  #         name: blob # Specifies which name is available on `context`
  #         path: blob-sample/{blobName}
  #         connection: AzureWebJobsStorage # App Setting/environment variable which contains Storage Account Connection String
  # storageQueue:
  #   handler: src/handlers/storageQueue.printMessage
  #   events:
  #     - queue: queue-sample
  #       x-azure-settings:
  #         name: message # Specifies which naem is available on `context`
  #         connection: AzureWebJobsStorage
  # timer:
  #   handler: src/handlers/timer.printMessage
  #   events:
  #     - timer:
  #       x-azure-settings:
  #         schedule: '*/10 * * * * *'
  # eventhub:
  #   handler: src/handlers/eventHub.printMessage
  #   events:
  #     - eventHub:
  #       x-azure-settings:
  #         name: eventHubMessages # Specifies which name it's available on `context`
  #         eventHubName: sample-hub # Specifies the Name of the Event Hub
  #         consumerGroup: $Default # Specifies the consumerGroup to listen with
  #         connection: EVENT_HUBS_CONNECTION # App Setting/environment variable which contains Event Hubs Namespace Connection String
  # serviceBusQueue:
  #   handler: src/handlers/serviceBusQueue.printMessage
  #   events:
  #     - serviceBus:
  #       x-azure-settings:
  #         name: message # Specifies which name is available on `context`
  #         queueName: sample-queue # Name of the service bus queue to consume
  #         connection: SERVICE_BUS_CONNECTION # App Setting/environment variable variable which contains Service Bus Namespace Connection String
  # serviceBusTopic:
  #   handler: src/handlers/serviceBusTopic.printMessage
  #   events:
  #     - serviceBus:
  #       x-azure-settings:
  #         name: message # Specifies which name it's available on `context`
  #         topicName: sample-topic # Name of the service bus topic to consume
  #         subscriptionName: sample-subscription # Name of the topic subscription to retrieve from
  #         connection: SERVICE_BUS_CONNECTION # App Setting/environment variable variable which contains Service Bus Namespace Connection String
```
