### ISSUE TITLE
Eventhub trigger cardinality not being set in 2.x.x

### ISSUE THREAD

**Issue by Rapol** [serverless/serverless-azure-functions#478]
# This is a Bug Report

## Description

- What went wrong?

Deploying an event hub trigger doesn't set the cardinality in 2.0.9. This worked at least on 1.0.2-16 which we were using before upgrading to 2.x.x.

- What did you expect should have happened?

sls deploy should generate the correct host.json for event hub trigger and include the cardinality

- What was the config you used?

```
processEventHubLogs:
    handler: src/eventHubHandler
    events:
      - eventHub:
        x-azure-settings:
          name: fileMessages
          path: EVENT_HUB_PATH
          connection: EVENT_HUB_CONNECTION_STRING
          cardinality: many
```
## Additional Data

- **_Serverless Framework Version you're using_**: 1.67.0
- **_Serverless CLI Version you're using_**: 2.3.0
- **_Serverless Azure Plugin Version you're using_**: 2.0.9
- **_Operating System_**: mac os

We found that in the default bindings (bindings.json), the binding of type eventhubTrigger cardinality setting was removed in 2.0.0. This setting needs to be added back

```
{
                    "name": "cardinality",
                    "value": "enum",
                    "required": false,
                    "defaultValue": "many",
                    "enum": [
                        {
                            "value": "one",
                            "display": "One"
                        },
                        {
                            "value": "many",
                            "display": "Many"
                        }
                    ],
                    "label": "$eventHubTrigger_cardinality_label",
                    "help": "$eventHubTrigger_cardinality_help"
                }
```
