### ISSUE TITLE
serviceBusQueue sample does not consume messages

### ISSUE THREAD

**Issue by psurma** [serverless/serverless-azure-functions#485]
# This is a Bug Report

## Description

- What went wrong?
Deploying the serviceBusQueue example does not work as expected.
- What did you expect should have happened?
The function defined should be invoked when a message is sent to the service bus queue.
- What was the config you used?
```
  serviceBusQueue:
    handler: src/handlers/serviceBusQueue.printMessage
    events:
      - serviceBus:
        x-azure-settings:
          name: item # Specifies which name is available on `context`
          queueName: tester # Name of the service bus queue to consume
          connection: tester_SERVICEBUS # App Setting/environment variable variable which contains Service Bus Namespace Connection String
          accessRights: listen

```
- What stacktrace or error message from your provider did you see?
No errors or activity

Similar or dependent issues:

none

## Additional Data

I create a ServiceBus Queue manually and a Shared Access Policy for (Listen) in the Service Bus Namespace.  I used the Primary Connection String as the Application Configuration Value for tester_SERVICEBUS

- **_Serverless Framework Version you're using_**: 1.74.1
- **_Serverless CLI Version you're using_**: 
- **_Serverless Azure Plugin Version you're using_**: 1.0.2
- **_Operating System_**: darwin
- **_Stack Trace_**: none
- **_Provider Error messages_**:
