### ISSUE TITLE
Serverless function keeps being rebuilt indefinitely (Host configuration has changed. Signaling restart)

### ISSUE THREAD

**Issue by reflash** [serverless/serverless-azure-functions#503]
# This is a Bug Report

## Description

- What went wrong?
Function keeps triggering restart
[27/09/2020 00:38:31] File change of type 'Changed' detected for '<...>/graphql/function.json'    
[27/09/2020 00:38:31] Host configuration has changed. Signaling restart
Seems that my build changes some files in node_modules which triggers rebuild indefinitely. I was trying to add .funcignore to ignore those changes, but with no success
- What did you expect should have happened?
Changes to be built once
- What was the config you used?
```yml
service: name

provider:
  name: azure
  location: Germany West Central
  runtime: nodejs12

plugins:
  - serverless-azure-functions

package:
  exclude:
    - .funcignore

functions:
  graphql:
    handler: dist/endpoint
    events:
      - http: true
        x-azure-settings:
          name: req
      - http: true
        x-azure-settings:
          name: $return
          direction: out
```
- What stacktrace or error message from your provider did you see?

Similar or dependent issues:

## Additional Data

- **_Serverless Framework Version you're using_**: 2.1.1
- **_Serverless CLI Version you're using_**:
- **_Serverless Azure Plugin Version you're using_**: 2.0.13
- **_Operating System_**: OS X Catalina
- **_Stack Trace_**:
- **_Provider Error messages_**:
