### ISSUE TITLE
Error: Binding  direction not supported

### ISSUE THREAD

**Issue by blomm** [serverless/serverless-azure-functions#507]
# This is a Bug Report

## Description

- What went wrong? : when running sls offline or sls deploy, this error pops up
- What did you expect should have happened? publish to azure with a function that allows me to read from cosmosDB
- What was the config you used? (pretty much straight from [the docs](https://www.serverless.com/framework/docs/providers/azure/events/cosmosdb/))

functions:
  sampleQuery:
    handler: src/handlers/sample.query
    events:
      - http: true
        methods:
          - POST
        authLevel: anonymous
      - cosmosDB:
        direction: out
        name: record # name of input parameter in function signature
        databaseName: sampleDB
        collectionName: sampleCollection
        connectionStringSetting: COSMOS_DB_CONNECTION # name of appsetting with the connection string
        createIfNotExists: true # A boolean value to indicate whether the collection is created when it doesn't exist.
  

- What stacktrace or error message from your provider did you see?

Similar or dependent issues:

- I thought it a bit strange that the error message has 2 spaces between Binding and direction, so i've play around with the indentation a bit, and....

- Strangely, if I indent all the cosmosDB properties, I then see this [issue](https://github.com/serverless/serverless-azure-functions/issues/474): "Required property connectionStringSetting is missing for binding:cosmosDB"
(and I've set this property in local.settings.json)

## Additional Data

Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              10.16.0
     Framework Version:         2.8.0
     Plugin Version:            4.1.1
     SDK Version:               2.3.2
     Components Version:        3.2.7

- **_Provider Error messages_**:
Error: Binding  direction not supported
      at Function.<anonymous> (/Users/michaelblom/development/nanook/reporting-config-api/node_modules/serverless-azure-functions/lib/shared/utils.js:99:39)

**Comment by blomm** [comment]
It's essentially not liking any bindings under cosmosDB

**Comment by blomm** [comment]
I added some extra logging:

```
if (index < 0) {
                                console.log("acceptable binding types: " + JSON.stringify(bindingTypes))
                                throw new Error("Binding  " + bindingType + " not supported");
                            }
```


what it printed out was this:
`["timerTrigger","eventHubTrigger","eventHub","queue","queueTrigger","blob","blob","blobTrigger","apiHubFile","apiHubFile","apiHubFileTrigger","apiHubTable","apiHubTable","httpTrigger","http","serviceBusTrigger","serviceBus","manualTrigger","table","table","cosmosDB","cosmosDB","cosmosDBTrigger","mobileTable","mobileTable","notificationHub","sendGrid","twilioSms","bot","bot"]`

**Comment by blomm** [comment]
when I don't include any properties under cosmosDB, it says:
`Error: Required property connectionStringSetting is missing for binding:cosmosDB`
When I add connectionStringSetting (or anything under cosmosDB) it says:
`Error: Binding  connectionStringSetting not supported`

**Comment by jis260** [comment]
I have been having similar issues with the sendGrid binding. I also just tried the cosmosDB binding and I found that I need to use "x-azure-settings:" like:

```
- cosmosDB:
  x-azure-settings:
    direction: out
    name: record # name of input parameter in function signature
    databaseName: databaseName
    collectionName: collectionName
    connectionStringSetting: COSMOS_DB_CONNECTION # name of appsetting with the connection string
    createIfNotExists: false # A boolean value to indicate whether the collection is created when it doesn't exist.
```

If I look at the Azure function "function.json" it has:
```
{
      "type": "cosmosDB",
      "direction": "out",
      "name": "record",
      "databaseName": "databaseName",
      "collectionName": "collectionName",
      "createIfNotExists": false,
      "connectionStringSetting": "COSMOS_DB_CONNECTION"
 } 
```

I also found that if you don't have another output binding specified then the "name" property gets ignored and is set to "$return". So I set it like:
```
    events:
      - http: true
        methods:
          - POST
        authLevel: function
      - http:
        x-azure-settings:
          direction: out # Specifies the Name of the Event Hub   
      - cosmosDB:
        x-azure-settings:
          direction: out
          name: doc
          databaseName: databaseName
          collectionName: collectionName
          connectionStringSetting: COSMOS_DB_CONNECTION # name of appsetting with the connection string
          createIfNotExists: false # A boolean value to indicate whether the collection is created when it doesn't exist.  
``` 

In the function.json it displays as:
```
   {
      "type": "httpTrigger",
      "direction": "in",
      "name": "req",
      "authLevel": "function",
      "methods": [
        "POST"
      ]
    },
    {
      "type": "http",
      "direction": "out",
      "name": "$return"
    },
    {
      "type": "cosmosDB",
      "direction": "out",
      "name": "doc",
      "databaseName": "gnpdr",
      "collectionName": "metadata",
      "createIfNotExists": false,
      "connectionStringSetting": "COSMOS_DB_CONNECTION"
    }
```
For sendGrid this does not seem to work.
**Unfortunately, I have been unable to get the output binding working correctly. Whenever, the cosmosDB binding is included and I try to call the Azure function it gives a 404 not found error.**
