### ISSUE TITLE
Template / Path Parameters in function > apim > operations > urlTemplate

### ISSUE THREAD

**Issue by jis260** [serverless/serverless-azure-functions#522]
# Issue: Setting Template / Path Parameters

## Description

- What went wrong?
Deploying when a template / path parameter is defined results in an error:

- What did you expect should have happened?
I was hoping that this would define the template / path parameter on the API.

- What was the config you used?
The template / path parameter is being specified like this:
```
    apim:
      # The API to attach this operation
      api: test-api-v1
      # The Backend use for the operation
      backend: test-backend
      operations:
        - method: get
          urlTemplate: /user/{param}
          displayName: GetUserResourceToken
```
{param} is the template / path parameter that I would like it to set. This is similar syntax to what I use for AWS Lambda functions, but I am not sure where I define the parameter so that Azure API Management expects it as a Template parameters. If you use the same syntax from the Azure portal then it does set a Template Parameter with name: param. I would like to be able to do this from the serverless.yml.

- What stacktrace or error message from your provider did you see?
```
Serverless: {
  "code": "ValidationError",
  "message": "One or more fields contain incorrect values:",
  "details": [
    {
      "code": "ValidationError",
      "message": "All template parameters used in the UriTemplate must be defined in the Operation, and vice-versa.",
      "target": "templateParameters"
    }
  ]
}
```

## Additional Data
> serverless --version
**Framework Core: 2.20.1
Plugin: 4.4.2
SDK: 2.3.2
Components: 3.5.1**

> npm view serverless-azure-functions version
**2.1.0**

**Comment by jis260** [comment]
So after looking at apimService.js

I see that the urlTemplate will be inferred from the route parameter **if** urlTemplate is not set.
So removing the operations: settings and then specifying:

```
    events:
      - http: true
        methods:
          - GET
        authLevel: function
        route: user/{sub}
```
Seems to do the trick.

I ended up editing apimService.js 
if (!functionConfig.apim) 
to
if (!functionConfig.apim.operations)

So that I can still use the api properties for setting api: and backend:

**Comment by bharathtakkalki** [comment]
@jis260 I'm also trying to set path param in operations and ran into the same error, any solution?

**Comment by jis260** [comment]
Hi @bharathtakkalki, I got it working using the change above. I had to edit apimService.js as per the above.

Also I do not specify **operations:** in the apim configuration. Instead on the functions themselves, I am specifying the **route:**

So the structure of the serverless.yml looks like this:
```  
apim:
    name: ${self:custom.config.apimName}
    apis:
      - name:     
    backends:
      - name: 
 functions:
  example:
    handler:
    name:
    events:
      - http: true
        methods:
          - POST
        authLevel: function
        route: user/{sub}
      - http: true
        direction: out           
    apim:
      api: 
      backend: 
```
apimService.js
\node_modules\serverless-azure-functions\lib\services\apimService.js

Been a while since I looked at it, but it was around lines 240/241/242 that I changed:

```
                        // if (!functionConfig.apim) {
                        if (!functionConfig.apim.operations) {
                            operations = httpConfig.methods.map(function (method) {
``` 
I ended up adding lots of print statements to debug and understand what the modules were doing.

**Comment by khaosdoctor** [comment]
So for anyone going through this, I found a solution without the need of changing the source.

You can actually set the same return from the `apimService.ts` file within the `functions.functionName.apim.operations` like this:

```yaml
  getResult:
    handler: api/handlers.getResult
    apim:
      api: my-serverless
      backend: some-backend
      operations:
        - method: get
          urlTemplate: /api/results/{id}
          displayName: Get result
          templateParameters:
            - name: id
              type: string
              required: true
              description: Result ID
    events:
      - http: true
        authLevel: anonymous
        methods:
          - GET
```

Also, if you don't want to handle it yourself, you can remove that section altogether, but then you won't be able to set APIM configs and will have to rely on `events[0].route`:

```yml
  getResult:
    handler: api/handlers.getResult
    events:
      - http: true
        route: /api/results/{id}
        authLevel: anonymous
        methods:
          - GET
```
