### ISSUE TITLE
Serverless Framework  is not setting the  "leaseCollectionPrefix" with Cosmosdb trigger

### ISSUE THREAD

**Issue by wolverinethegeneral** [serverless/serverless-azure-functions#554]
Hi everyone,

I am deploying some functions in azure with the cosmosdb trigger, but when I define it on the serverless.yml:
```yaml
      - cosmosDB: true
        x-azure-settings:
          name: documents # name of input parameter in function signature
          databaseName: dbName
          direction: in
          leaseCollectionName: leases
          leaseCollectionPrefix: dbPrefix
          connectionStringSetting: myConnectionString
          collectionName: collection_name
          createLeaseCollectionIfNotExists: true
```

and when deploy i get:

![image](https://user-images.githubusercontent.com/85257970/120550258-3a0a0280-c3ba-11eb-88da-ce02034c5d44.png)

with no leaseCollectionPrefix

Can anyone help, please
