### ISSUE TITLE
Incorrect Service Bus binding parsing

### ISSUE THREAD

**Issue by truztee** [serverless/serverless-azure-functions#57]
This is the config I use in serverless.yaml
```yaml
functions:
  importJob:
     handler: handler.importJob
     events:
       - serviceBus:
         x-azure-settings:
           name: item
           queueName: import-queue
           accessRights: listen
           connection : ServiceBusConnection
```
This is the parsed binding result:

```javascript
{ type: 'serviceBusTrigger',
  direction: 'in',
  name: 'item',
  queueName: 'import-queue',
  topicName: 'mysbtopic',
  subscriptionName: 'mysubscription',
  connection: 'ServiceBusConnection',
  accessRights: 'listen' 
}
```

There are both queueName and topicName defined in the binding output along with subscriptionName which should not be there if queueName is defined.
