### ISSUE TITLE
The bindings for signalR is now getting assigned for the negotiate function

### ISSUE THREAD

**Issue by Vikas252** [serverless/serverless-azure-functions#674]
# This is a Bug Report

Expected function,json
```
{
  "disabled": false,
  "bindings": [
    {
      "type": "httpTrigger",
      "direction": "in",
      "name": "req",
      "route": "negotiate",
      "authLevel": "function",
      "methods": ["POST"]
    },
    {
      "type": "http",
      "direction": "out",
      "name": "res"
    },
    {
      "type": "signalRConnectionInfo",
      "name": "connectionInfo",
      "hubName": "serverless",
      "connectionStringSetting": "AzureSignalRConnectionString",
      "direction": "in"
    }
  ],
  "entryPoint": "negotiate",
  "scriptFile": "../dist/server.js"
}
```

Current function.json when deployed:
```
{
  "disabled": false,
  "bindings": [
    {
      "type": "httpTrigger",
      "direction": "in",
      "name": "req",
      "route": "negotiate",
      "authLevel": "function",
      "methods": ["POST"]
    },
    {
      "type": "http",
      "direction": "out",
      "name": "res"
    }
  ],
  "entryPoint": "negotiate",
  "scriptFile": "../dist/server.js"
}
```
serverless.yml file
```

negotiate:
    handler: dist/server.negotiate
    events:
      - http: true
        route: negotiate
        methods:
          - POST
    outputs:
      connectionInfo:
        type: signalRConnectionInfo
        name: connectionInfo
        hubName: serverless
        connectionStringSetting: AzureSignalRConnectionString
        direction: in

```

## Description

- What went wrong?
    **Binding is not getting stored in the function.json**
- What did you expect should have happened?
    **The above function.json that is expected should be a result**
- What was the config you used?
     **Azure functions core tools - 4 version
     SignalR instance for the connection in serverless mode**

## Additional Data

- **_Serverless Framework Version you're using_**:
```
Framework Core: 3.31.0 (local) 3.31.0 (global)
Plugin: 6.2.3
SDK: 4.3.2
```
- **_Serverless Azure Plugin Version you're using_**: 
``` 
  - serverless-azure-functions
  - serverless-plugin-scripts
  - serverless-plugin-common-excludes
  - serverless-plugin-include-dependencies
  - serverless-dotenv-plugin
```
- **_Operating System_**: `` Win 11``
