### ISSUE TITLE
Python Azure function queue name always set to $return

### ISSUE THREAD

**Issue by nimish-cd** [serverless/serverless-azure-functions#679]
# This is a Bug Report

## Description

- What went wrong?

I am creating Azure function with python runtime. Setting output queue binding and name of the queue. Irrespective of whether name is set or not, its always setting binding queue name to `$return` for first out queue binding.

Function.json:
```
[
    {
      "type": "queueTrigger",
      "direction": "in",
      "name": "inputQueueName",
      "queueName": "inputQueue",
      "connection": "AzureWebJobsStorage"
    },
    {
      "type": "queue",
      "direction": "out",
      "name": "$return",
      "queueName": "outputQueue",
      "connection": "AzureWebJobsStorage"
    },
    {
      "type": "queue",
      "direction": "out",
      "name": "outputQueueName2",
      "queueName": "outputQueue2",
      "connection": "AzureWebJobsStorage"
    }
  ]
```

- What did you expect should have happened?
As name is provided for queue in event, it should be populated in function.json instead of `$return`

- What was the config you used?
Serverless.yml:
```
functions:
  queueTrigger:
    handler: handler.main
    runtime: python3.8
    events:
      - queue: inputQueue
        name: inputQueueName
        connection: AzureWebJobsStorage

      - queue: outputQueue
        direction: out
        name: outputQueueName
        connection: AzureWebJobsStorage
  
      - queue: outputQueue2
        direction: out
        name: outputQueueName2
        connection: AzureWebJobsStorage

```

- What stack trace or error message from your provider did you see?

Similar or dependent issues:

- #12345

## Additional Data

- **_Serverless Framework Version you're using_**:
Framework Core: 3.38.0 (local) 3.38.0 (global)
Plugin: 7.2.0
SDK: 4.5.1

func -v
4.0.5455
- **_Serverless CLI Version you're using_**:
- **_Serverless Azure Plugin Version you're using_**:
- **_Operating System_**: macOs 14.2.1 (23C71)
- **_Stack Trace_**:
- **_Provider Error messages_**:
