### ISSUE TITLE
Azure + ServiceBus: The connection key gets overridden everytime a deploy happens

### ISSUE THREAD

**Issue by arunshan** [serverless/serverless-azure-functions#73]
This issue is in regards to `ServiceBus` event with `out` direction using serverless.

serverless.yml
```
service: serverless-translator
provider:
  name: azure
  location: West US

plugins:
  - serverless-azure-functions

package:
  exclude:
    - .gitignore
    - package.json
    - config.template.json
    - README.md
    - .git/**
    - tests/*

functions:
  ingest:
    handler: operations/webhooks.ingest
    events:
      - http: true
        x-azure-settings:
          methods:
            - POST
          route: translate
          authLevel: anonymous
      - serviceBus:
        x-azure-settings:
          name: $return
          queueName: layerqueue
          accessRights: manage
          connection: ServiceBusConnection
          direction: out
  verify:
    handler: operations/webhooks.verify
    description: 'Webhook verification endpoint'
    events:
      - http: true
        x-azure-settings:
          methods:
            - GET
          route: translate
          authLevel: anonymous
      - http: true
        x-azure-settings:
          type: http
          direction: out
          name: res
```

Set the `ServiceBusConnection` app settings as mentioned in the documentation. Screenshot below.

!['Service Bus Connection'](https://cl.ly/3b2T20250R3j/Image%202017-06-07%20at%2012.48.36%20PM.png)

But for some reason, everytime I deploy the function using `serverless deploy` the `ServiceBusConnection` property is overridden or removed from the app settings on the azure portal.

Any help here is greatly appreciated.

**Comment by vjrantal** [comment]
@arunshan I believe the way serverless-azure-functions currently sets the properties overrides the changes that you make in the portal.

To support scenarios like this, you can set the variable in your `serverless.yml`. Here is an example:

```
provider:
  name: azure
  location: North Europe
  environment:
    EVENT_HUB_CONNECTION: "Endpoint=sb://..."
```

You can also avoid putting the values to the source code by referring to environment variables within the host on which you run the serverless commands:

```
provider:
  name: azure
  location: North Europe
  environment:
    EVENT_HUB_CONNECTION: ${env:EVENT_HUB_CONNECTION}
```
