### ISSUE TITLE
route in serverless.yaml causes error when serverless invoke is called

### ISSUE THREAD

**Issue by hoffmannjan** [serverless/serverless-azure-functions#86]
Hi,

when I've got in my config something like this

```
list:
  handler: list.list
  events:
    - http: true
      x-azure-settings:
        route: example
        authLevel: anonymous
    - http: true
      x-azure-settings:
        name: res
        direction: out
```

and I call

`serverless invoke -f list`

got an error

```
Error
    at module.exports.logError (/usr/local/lib/node_modules/serverless/lib/classes/Error.js:94:11)
    at initializeErrorReporter.then.catch.e (/usr/local/lib/node_modules/serverless/bin/serverless:42:3)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at __dirname (/usr/local/lib/node_modules/serverless/bin/serverless:40:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless/bin/serverless:43:4)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
```

Everything works fine in portal.azure.com and when requesting function url throught CURL.
